# HTTP Server
server:
  port: ${PORT:2222}   # HTTP port

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    preferIpAddress: true      

logging:
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'DEBUG'
    org.springframework.cloud: 'DEBUG'
    org.springframework.web: 'DEBUG'
    com.atsistemas: 'DEBUG'

cygnus:
  sadr:
    name: sadr
    pingUrl: http://${cygnus.sadr.name}/sadr/ping/

spring:
   rabbitmq:
     host: localhost
     port: 5672
     username: guest
     password: guest
